apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-text-classification
  labels:
    app: flask-app-text-classification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-text-classification
  template:
    metadata:
      labels:
        app: flask-app-text-classification
    spec:
      containers:
      - name: flask-app-text-classification
        image: 687407529776.dkr.ecr.ap-south-1.amazonaws.com/flask-app-text-classification:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app-text-classification
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000